### PR TITLE
Feat/46

### PR DESCRIPTION
**Pull request by rndquu**
Related to https://github.com/ubiquibot/permit-generation/issues/46

P.S. Some `ts` types are updated, not sure if it breaks something

### CODE REVIEW

**Review by 0x4007 — COMMENTED** [review]
Can you explain why issue id has collisions? This should be unique

**Comment by Keyrxng** [comment]
https://github.com/ubiquibot/conversation-rewards/blob/9853408f7735bebc50eb2679f118ca82b3cac0c0/src/parser/permit-generation-module.ts#L49

The permit-rewards plugin is passing in issue.id so we'll need to update that or permits will be broken

**Review by gentlementlegen — APPROVED** [review]
I am good with the changes, but how come this didn't break before?

**Comment by rndquu** [comment]
> Can you explain why issue id has collisions? This should be unique

I remember there was a long github thread at https://github.com/orgs/community/discussions regarding why `node_id` should be used instead of `id` but I couldn't find it. The closest thing I found is [this](https://github.com/orgs/community/discussions/29784) post. 

In short:
1. `node_id` supersedes `id` and is guaranteed to be unique as stated [here](https://docs.github.com/en/graphql/guides/migrating-graphql-global-node-ids): `These IDs will be unique, therefore you can rely on them directly as references.`
2. Github object id's may be changed over time as mentioned [here](https://github.com/orgs/community/discussions/29784)

`node_id` is basically a base64 encoded string of `{type_id}:{type_name}{resource_id}`.

Example:
```
$ echo "MDEwOlJlcG9zaXRvcnkxMzkwOTU1Mzc=" | base64 --decode
010:Repository139095537
``` 

So if multiple repositories (or issues, PRs, users, etc...) have the same resource id their `node_id` will be different because of the `type_name` used.

**Comment by rndquu** [comment]
> https://github.com/ubiquibot/conversation-rewards/blob/9853408f7735bebc50eb2679f118ca82b3cac0c0/src/parser/permit-generation-module.ts#L49
> 
> The conversation-rewards plugin is passing in issue.id so we'll need to update that or permits will be broken

Let me double check

**Comment by rndquu** [comment]
> I am good with the changes, but how come this didn't break before?

It was broken. `conversation-rewards` plugin incorrectly [passes](https://github.com/ubiquibot/conversation-rewards/blob/9853408f7735bebc50eb2679f118ca82b3cac0c0/src/parser/permit-generation-module.ts#L47) issue number instead of issue id hence the collision occurred. 

> https://github.com/ubiquibot/conversation-rewards/blob/9853408f7735bebc50eb2679f118ca82b3cac0c0/src/parser/permit-generation-module.ts#L49
> 
> The conversation-rewards plugin is passing in issue.id so we'll need to update that or permits will be broken

I'll make a PR

**Review by Keyrxng — APPROVED** [review]

**Pull request merged**
